language: php

php:
  - 5.6
  - 7.0
  - 7.1

install:
  - composer install --dev --no-interaction

script:
  - phpunit --tap --coverage-clover build/logs/clover.xml

after_script:
  - bash bin/codeclimate.sh
